### ISSUE TITLE
Add guidance for eventType vs type

### ISSUE THREAD

**Issue by EliLawrence** [iobis/manual#92]
Current eventType DwC guidelines https://dwc.tdwg.org/terms/#dwc:eventType
In the [Manual](https://manual.obis.org/checklist.html) we currently suggest type or eventType. I think it would be good to provide some more guidance on which kinds of standard vocab could be used to fill this field.
Happy to hear any suggestions

**Comment by laurabrenskelle** [comment]
`dc:type` is a term from Dublin Core that has a [controlled vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#) to describe a resource type. Given this, it should not be used to describe types of events.

**Comment by timvdstap** [comment]
I agree that it would be good to have some guidance on eventType vs type (vs eventRemarks). A few notes / questions I have around these terms:

- If I'm not mistaken, I have seen _type_ being used in the past as an optional term, with free text, often times describing the hierarchy of sampling nature (project, cruise, station, sample, subsample etc). This information would now be included in _eventType_, right?
- I agree with @laurabrenskelle that _type_ should not be used to describe the type of event, but rather the resource type. I'm wondering whether this distinction should more clearly be made in the vocabulary (e.g. resourceType and eventType), especially given that both can be included in the Event core?
- I believe _eventType_ is not currently included in the latest version of the IPT: should use _eventRemarks_ instead until this is updated?

**Comment by tucotuco** [comment]
Darwin Core [adopted](https://dwc.tdwg.org/terms/#dc:type) the Dublin Code term dc:type with its recommended DCMI Type vocabulary. It should not be used for anything other than expressions of type from that vocabulary. As this is an adopted term, it's name, label, and definition are all preserved from the source as a principle.

The Darwin Core term [dwc:eventType](https://dwc.tdwg.org/terms/#dwc:eventType) was ratified in 2023 and included in GBIF's [Event](https://rs.gbif.org/core/dwc_event_2024-02-19.xml) and [Occurrence](https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml) schemas since February 2024. Any IPT that does not show this term enabled simply hasn't been updated to the latest schema.

**Comment by laurabrenskelle** [comment]
Thanks, @tucotuco!

**Comment by timvdstap** [comment]
Thank you @tucotuco - I have contacted our Node Manager to see if our IPT instance is up to date, or whether there's a different reason I don't see eventType in the schema.

**Comment by EliLawrence** [comment]
Thanks everyone for the discussion! Indeed I believe type was used in the past for documenting event type. I've updated the manual now to remove the recommendation of type associated with event data, and added eventType usage instead (here: https://manual.obis.org/darwin_core.html#event). 

If there's more suggestions or feedback to add clarification let me know otherwise I will close the issue
